// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// info_observed_covariate
List info_observed_covariate(arma::cube yyikj, arma::ucube ttikj, int nind, int ndimy, arma::umat nobsik, arma::imat statebegin, arma::imat stateend, arma::imat timebegin, arma::imat timeend, arma::ivec ntransition, arma::imat possible_transitions, int nstates, arma::mat zzi, int ndimz, arma::mat xxi, int ndimx, arma::field<arma::mat> basismatrix_long, arma::uvec nbas_long, arma::mat alleeieval, int ntimepoints, List result_est);
RcppExport SEXP _jointmultistate_info_observed_covariate(SEXP yyikjSEXP, SEXP ttikjSEXP, SEXP nindSEXP, SEXP ndimySEXP, SEXP nobsikSEXP, SEXP statebeginSEXP, SEXP stateendSEXP, SEXP timebeginSEXP, SEXP timeendSEXP, SEXP ntransitionSEXP, SEXP possible_transitionsSEXP, SEXP nstatesSEXP, SEXP zziSEXP, SEXP ndimzSEXP, SEXP xxiSEXP, SEXP ndimxSEXP, SEXP basismatrix_longSEXP, SEXP nbas_longSEXP, SEXP alleeievalSEXP, SEXP ntimepointsSEXP, SEXP result_estSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type yyikj(yyikjSEXP);
    Rcpp::traits::input_parameter< arma::ucube >::type ttikj(ttikjSEXP);
    Rcpp::traits::input_parameter< int >::type nind(nindSEXP);
    Rcpp::traits::input_parameter< int >::type ndimy(ndimySEXP);
    Rcpp::traits::input_parameter< arma::umat >::type nobsik(nobsikSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type statebegin(statebeginSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type stateend(stateendSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type timebegin(timebeginSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type timeend(timeendSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ntransition(ntransitionSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type possible_transitions(possible_transitionsSEXP);
    Rcpp::traits::input_parameter< int >::type nstates(nstatesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type zzi(zziSEXP);
    Rcpp::traits::input_parameter< int >::type ndimz(ndimzSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xxi(xxiSEXP);
    Rcpp::traits::input_parameter< int >::type ndimx(ndimxSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type basismatrix_long(basismatrix_longSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type nbas_long(nbas_longSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alleeieval(alleeievalSEXP);
    Rcpp::traits::input_parameter< int >::type ntimepoints(ntimepointsSEXP);
    Rcpp::traits::input_parameter< List >::type result_est(result_estSEXP);
    rcpp_result_gen = Rcpp::wrap(info_observed_covariate(yyikj, ttikj, nind, ndimy, nobsik, statebegin, stateend, timebegin, timeend, ntransition, possible_transitions, nstates, zzi, ndimz, xxi, ndimx, basismatrix_long, nbas_long, alleeieval, ntimepoints, result_est));
    return rcpp_result_gen;
END_RCPP
}
// info_partial_covariate
List info_partial_covariate(arma::cube yyikj, arma::ucube ttikj, int nind, int ndimy, arma::umat nobsik, arma::imat statebegin, arma::imat stateend, arma::imat timebegin, arma::imat timeend, arma::ivec ntransition, arma::imat possible_transitions, int nstates, arma::mat zzi, int ndimz, arma::mat xxi, int ndimx, arma::field<arma::mat> basismatrix_long, arma::uvec nbas_long, arma::mat alleeieval, int ntimepoints, List result_est);
RcppExport SEXP _jointmultistate_info_partial_covariate(SEXP yyikjSEXP, SEXP ttikjSEXP, SEXP nindSEXP, SEXP ndimySEXP, SEXP nobsikSEXP, SEXP statebeginSEXP, SEXP stateendSEXP, SEXP timebeginSEXP, SEXP timeendSEXP, SEXP ntransitionSEXP, SEXP possible_transitionsSEXP, SEXP nstatesSEXP, SEXP zziSEXP, SEXP ndimzSEXP, SEXP xxiSEXP, SEXP ndimxSEXP, SEXP basismatrix_longSEXP, SEXP nbas_longSEXP, SEXP alleeievalSEXP, SEXP ntimepointsSEXP, SEXP result_estSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type yyikj(yyikjSEXP);
    Rcpp::traits::input_parameter< arma::ucube >::type ttikj(ttikjSEXP);
    Rcpp::traits::input_parameter< int >::type nind(nindSEXP);
    Rcpp::traits::input_parameter< int >::type ndimy(ndimySEXP);
    Rcpp::traits::input_parameter< arma::umat >::type nobsik(nobsikSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type statebegin(statebeginSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type stateend(stateendSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type timebegin(timebeginSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type timeend(timeendSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ntransition(ntransitionSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type possible_transitions(possible_transitionsSEXP);
    Rcpp::traits::input_parameter< int >::type nstates(nstatesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type zzi(zziSEXP);
    Rcpp::traits::input_parameter< int >::type ndimz(ndimzSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xxi(xxiSEXP);
    Rcpp::traits::input_parameter< int >::type ndimx(ndimxSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type basismatrix_long(basismatrix_longSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type nbas_long(nbas_longSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alleeieval(alleeievalSEXP);
    Rcpp::traits::input_parameter< int >::type ntimepoints(ntimepointsSEXP);
    Rcpp::traits::input_parameter< List >::type result_est(result_estSEXP);
    rcpp_result_gen = Rcpp::wrap(info_partial_covariate(yyikj, ttikj, nind, ndimy, nobsik, statebegin, stateend, timebegin, timeend, ntransition, possible_transitions, nstates, zzi, ndimz, xxi, ndimx, basismatrix_long, nbas_long, alleeieval, ntimepoints, result_est));
    return rcpp_result_gen;
END_RCPP
}
// lik_covariate
List lik_covariate(arma::cube yyikj, arma::ucube ttikj, int nind, int ndimy, arma::umat nobsik, arma::imat statebegin, arma::imat stateend, arma::imat timebegin, arma::imat timeend, arma::ivec ntransition, arma::imat possible_transitions, int nstates, arma::mat zzi, int ndimz, arma::mat xxi, int ndimx, arma::field<arma::mat> basismatrix_long, arma::uvec nbas_long, arma::mat alleeieval, int ntimepoints, List result_est);
RcppExport SEXP _jointmultistate_lik_covariate(SEXP yyikjSEXP, SEXP ttikjSEXP, SEXP nindSEXP, SEXP ndimySEXP, SEXP nobsikSEXP, SEXP statebeginSEXP, SEXP stateendSEXP, SEXP timebeginSEXP, SEXP timeendSEXP, SEXP ntransitionSEXP, SEXP possible_transitionsSEXP, SEXP nstatesSEXP, SEXP zziSEXP, SEXP ndimzSEXP, SEXP xxiSEXP, SEXP ndimxSEXP, SEXP basismatrix_longSEXP, SEXP nbas_longSEXP, SEXP alleeievalSEXP, SEXP ntimepointsSEXP, SEXP result_estSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type yyikj(yyikjSEXP);
    Rcpp::traits::input_parameter< arma::ucube >::type ttikj(ttikjSEXP);
    Rcpp::traits::input_parameter< int >::type nind(nindSEXP);
    Rcpp::traits::input_parameter< int >::type ndimy(ndimySEXP);
    Rcpp::traits::input_parameter< arma::umat >::type nobsik(nobsikSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type statebegin(statebeginSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type stateend(stateendSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type timebegin(timebeginSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type timeend(timeendSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ntransition(ntransitionSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type possible_transitions(possible_transitionsSEXP);
    Rcpp::traits::input_parameter< int >::type nstates(nstatesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type zzi(zziSEXP);
    Rcpp::traits::input_parameter< int >::type ndimz(ndimzSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xxi(xxiSEXP);
    Rcpp::traits::input_parameter< int >::type ndimx(ndimxSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type basismatrix_long(basismatrix_longSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type nbas_long(nbas_longSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alleeieval(alleeievalSEXP);
    Rcpp::traits::input_parameter< int >::type ntimepoints(ntimepointsSEXP);
    Rcpp::traits::input_parameter< List >::type result_est(result_estSEXP);
    rcpp_result_gen = Rcpp::wrap(lik_covariate(yyikj, ttikj, nind, ndimy, nobsik, statebegin, stateend, timebegin, timeend, ntransition, possible_transitions, nstates, zzi, ndimz, xxi, ndimx, basismatrix_long, nbas_long, alleeieval, ntimepoints, result_est));
    return rcpp_result_gen;
END_RCPP
}
// multi_covariate
List multi_covariate(arma::cube yyikj, arma::ucube ttikj, int nind, int ndimy, arma::umat nobsik, arma::imat statebegin, arma::imat stateend, arma::imat timebegin, arma::imat timeend, arma::ivec ntransition, arma::imat possible_transitions, int nstates, arma::mat zzi, int ndimz, arma::mat xxi, int ndimx, arma::field<arma::mat> basismatrix_long, arma::uvec nbas_long, arma::mat alleeieval, int ntimepoints, double factor_min, double factor_max, double tol, double tol2, int niter, bool csv, std::string tag);
RcppExport SEXP _jointmultistate_multi_covariate(SEXP yyikjSEXP, SEXP ttikjSEXP, SEXP nindSEXP, SEXP ndimySEXP, SEXP nobsikSEXP, SEXP statebeginSEXP, SEXP stateendSEXP, SEXP timebeginSEXP, SEXP timeendSEXP, SEXP ntransitionSEXP, SEXP possible_transitionsSEXP, SEXP nstatesSEXP, SEXP zziSEXP, SEXP ndimzSEXP, SEXP xxiSEXP, SEXP ndimxSEXP, SEXP basismatrix_longSEXP, SEXP nbas_longSEXP, SEXP alleeievalSEXP, SEXP ntimepointsSEXP, SEXP factor_minSEXP, SEXP factor_maxSEXP, SEXP tolSEXP, SEXP tol2SEXP, SEXP niterSEXP, SEXP csvSEXP, SEXP tagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type yyikj(yyikjSEXP);
    Rcpp::traits::input_parameter< arma::ucube >::type ttikj(ttikjSEXP);
    Rcpp::traits::input_parameter< int >::type nind(nindSEXP);
    Rcpp::traits::input_parameter< int >::type ndimy(ndimySEXP);
    Rcpp::traits::input_parameter< arma::umat >::type nobsik(nobsikSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type statebegin(statebeginSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type stateend(stateendSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type timebegin(timebeginSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type timeend(timeendSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type ntransition(ntransitionSEXP);
    Rcpp::traits::input_parameter< arma::imat >::type possible_transitions(possible_transitionsSEXP);
    Rcpp::traits::input_parameter< int >::type nstates(nstatesSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type zzi(zziSEXP);
    Rcpp::traits::input_parameter< int >::type ndimz(ndimzSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type xxi(xxiSEXP);
    Rcpp::traits::input_parameter< int >::type ndimx(ndimxSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type basismatrix_long(basismatrix_longSEXP);
    Rcpp::traits::input_parameter< arma::uvec >::type nbas_long(nbas_longSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type alleeieval(alleeievalSEXP);
    Rcpp::traits::input_parameter< int >::type ntimepoints(ntimepointsSEXP);
    Rcpp::traits::input_parameter< double >::type factor_min(factor_minSEXP);
    Rcpp::traits::input_parameter< double >::type factor_max(factor_maxSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type tol2(tol2SEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< bool >::type csv(csvSEXP);
    Rcpp::traits::input_parameter< std::string >::type tag(tagSEXP);
    rcpp_result_gen = Rcpp::wrap(multi_covariate(yyikj, ttikj, nind, ndimy, nobsik, statebegin, stateend, timebegin, timeend, ntransition, possible_transitions, nstates, zzi, ndimz, xxi, ndimx, basismatrix_long, nbas_long, alleeieval, ntimepoints, factor_min, factor_max, tol, tol2, niter, csv, tag));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jointmultistate_info_observed_covariate", (DL_FUNC) &_jointmultistate_info_observed_covariate, 21},
    {"_jointmultistate_info_partial_covariate", (DL_FUNC) &_jointmultistate_info_partial_covariate, 21},
    {"_jointmultistate_lik_covariate", (DL_FUNC) &_jointmultistate_lik_covariate, 21},
    {"_jointmultistate_multi_covariate", (DL_FUNC) &_jointmultistate_multi_covariate, 27},
    {NULL, NULL, 0}
};

RcppExport void R_init_jointmultistate(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
