# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

info_observed_covariate <- function(yyikj, ttikj, nind, ndimy, nobsik, statebegin, stateend, timebegin, timeend, ntransition, possible_transitions, nstates, zzi, ndimz, xxi, ndimx, basismatrix_long, nbas_long, alleeieval, ntimepoints, result_est) {
    .Call(`_jointmultistate_info_observed_covariate`, yyikj, ttikj, nind, ndimy, nobsik, statebegin, stateend, timebegin, timeend, ntransition, possible_transitions, nstates, zzi, ndimz, xxi, ndimx, basismatrix_long, nbas_long, alleeieval, ntimepoints, result_est)
}

info_partial_covariate <- function(yyikj, ttikj, nind, ndimy, nobsik, statebegin, stateend, timebegin, timeend, ntransition, possible_transitions, nstates, zzi, ndimz, xxi, ndimx, basismatrix_long, nbas_long, alleeieval, ntimepoints, result_est) {
    .Call(`_jointmultistate_info_partial_covariate`, yyikj, ttikj, nind, ndimy, nobsik, statebegin, stateend, timebegin, timeend, ntransition, possible_transitions, nstates, zzi, ndimz, xxi, ndimx, basismatrix_long, nbas_long, alleeieval, ntimepoints, result_est)
}

lik_covariate <- function(yyikj, ttikj, nind, ndimy, nobsik, statebegin, stateend, timebegin, timeend, ntransition, possible_transitions, nstates, zzi, ndimz, xxi, ndimx, basismatrix_long, nbas_long, alleeieval, ntimepoints, result_est) {
    .Call(`_jointmultistate_lik_covariate`, yyikj, ttikj, nind, ndimy, nobsik, statebegin, stateend, timebegin, timeend, ntransition, possible_transitions, nstates, zzi, ndimz, xxi, ndimx, basismatrix_long, nbas_long, alleeieval, ntimepoints, result_est)
}

multi_covariate <- function(yyikj, ttikj, nind, ndimy, nobsik, statebegin, stateend, timebegin, timeend, ntransition, possible_transitions, nstates, zzi, ndimz, xxi, ndimx, basismatrix_long, nbas_long, alleeieval, ntimepoints, factor_min = 0.2, factor_max = 0.8, tol = 1e-5, tol2 = 0.01, niter = 500L, csv = FALSE, tag = "0") {
    .Call(`_jointmultistate_multi_covariate`, yyikj, ttikj, nind, ndimy, nobsik, statebegin, stateend, timebegin, timeend, ntransition, possible_transitions, nstates, zzi, ndimz, xxi, ndimx, basismatrix_long, nbas_long, alleeieval, ntimepoints, factor_min, factor_max, tol, tol2, niter, csv, tag)
}

